name: Trigger auto deployment for builder-test-old-cloud

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/builder-test-old-cloud-AutoDeployTrigger-85c7966f-005f-450e-a827-17fe567c6663.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BUILDERTESTOLDCLOUD_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: liyitest.azurecr.io
          registryUsername: ${{ secrets.BUILDERTESTOLDCLOUD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUILDERTESTOLDCLOUD_REGISTRY_PASSWORD }}
          containerAppName: builder-test-old-cloud
          resourceGroup: yili-test-rg
          imageToBuild: liyitest.azurecr.io/builder-test-old-cloud:${{ github.sha }}
          
            

     

